# Generated by Django 5.0 on 2024-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_date_order_confirmed_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_item',
            field=models.BooleanField(default=False),
        ),
    ]
