# Generated by Django 5.0 on 2023-12-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_books_alter_store_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='is_item',
            field=models.BooleanField(default=False),
        ),
    ]
