# Generated by Django 5.0 on 2023-12-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_is_book_store_is_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
