# Generated by Django 5.0 on 2024-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issued_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
