# Generated by Django 5.0 on 2024-02-01 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_issued_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issued_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
