# Generated by Django 5.0 on 2024-01-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recieved_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='request_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='request_for',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
