# Generated by Django 5.0 on 2024-01-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_recieved_by_order_request_by_order_request_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='request_by',
            new_name='order_by',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='request_for',
            new_name='order_for',
        ),
    ]
