# Generated by Django 5.0 on 2024-02-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_subunit_order_subunit_quantity_order_with_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
