# Generated by Django 5.0 on 2024-02-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='with_tax',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='subunit',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('liter', 'Liter'), ('kg', 'Kilogram'), ('packets', 'Packets'), ('piece', 'Piece')], default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(choices=[('none', 'None'), ('liter', 'Liter'), ('kg', 'Kilogram'), ('packets', 'Packets'), ('piece', 'Piece')], max_length=20),
        ),
    ]
