# Generated by Django 5.0 on 2024-02-08 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_with_tax_ordergroup_total_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Given',
                'verbose_name_plural': 'Products Given',
            },
        ),
        migrations.CreateModel(
            name='ProductGivenDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_given', models.DateField()),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('product_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productgiven')),
            ],
            options={
                'verbose_name': 'Product Given Detail',
                'verbose_name_plural': 'Product Given Details',
            },
        ),
        migrations.AddField(
            model_name='productgiven',
            name='products',
            field=models.ManyToManyField(through='store.ProductGivenDetail', to='store.product'),
        ),
    ]
